//controlled by REST Client extension
###
POST https://dummyjson.com/products/add
Content-Type: application/x-www-form-urlencoded

title=Pumpkin&price=3.56

###
POST https://dummyjson.com/products/add
Content-Type: application/json

{
  "id": 101,
  "title": "Pumpkin",
  "price": "3.56"
}

###
http://localhost:3000

###
http://localhost:3000/products

###
https://wp-ecommerce-app.onrender.com/api/v1/products/28